# Generated by Django 4.1.7 on 2023-03-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(default=0),
        ),
    ]
